function NVMList=demo_getFixedNvmList()
NVMList={...
    struct('name', {'Fnvm_double'},'type', {'double'},'size', 1,'init', 0,'value',1), ...
    struct('name', {'Fnvm_int8'},'type', {'int8'},'size', 2,'init', 1,'value',[1 2]), ...
    struct('name', {'Fnvm_uint8'},'type', {'uint8'},'size', 1,'init', 0,'value',1), ...
    struct('name', {'Fnvm_boolean'},'type', {'boolean'},'size', 4,'init', 0,'value',[1 2 3 4]), ...
    struct('name', {'Fnvm_uint16'},'type', {'uint16'},'size', 2,'init', 1,'value',[1 2]), ...
    struct('name', {'Fnvm_int16'},'type', {'int16'},'size', 2,'init', 1,'value',[1 2]), ...
    struct('name', {'Fnvm_single'},'type', {'float'},'size', 1,'init', 0,'value',1), ...
    struct('name', {'Fnvm_int32'},'type', {'int32'},'size', 1,'init', 0,'value',1), ...
    struct('name', {'Fnvm_uint32'},'type', {'uint32'},'size', 4,'init', 0,'value',[1 2 3 4]), ...
};
end